// Export Handlers — MD / HTML / PDF / DOCX / ZIP bundling
import { Context } from 'hono'
import { db } from '../db/index.js'
import { projects, projectVersions } from '../db/schema.js'
import { eq, desc } from 'drizzle-orm'
import { marked } from 'marked'

// ─── Types ───────────────────────────────────────────────────────────────────

interface PrdSection {
  id: string
  name: string
  description: string
  priority: number
  is_mandatory: boolean
  content: string | null
  order: number
}

interface PrdData {
  tier: number
  tier_reason: string
  flags: string[]
  sections: PrdSection[]
  skipped_sections: Array<{ id: string; reason: string }>
}

interface Task {
  id: string
  phase: string
  feature: string
  task: string
  description: string
  effort: 'S' | 'M' | 'L'
  is_done: boolean
}

interface TasksData {
  tasks: Task[]
  generatedAt: string
}

type ExportFormat = 'md' | 'html' | 'pdf' | 'docx'

// ─── Helpers ─────────────────────────────────────────────────────────────────

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function renderMarkdownToHtml(md: string): string {
  const bodyHtml = marked.parse(md) as string
  return `<!DOCTYPE html>
<html lang="id">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PRD Export</title>
  <style>
    body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; line-height: 1.7; }
    h1 { font-size: 28px; border-bottom: 2px solid #C48A1A; padding-bottom: 12px; color: #1a1a1a; }
    h2 { font-size: 20px; margin-top: 36px; color: #1a1a1a; }
    h3 { font-size: 16px; color: #333; }
    code { background: #f4f0e8; padding: 2px 6px; border-radius: 3px; font-size: 13px; }
    pre { background: #f4f0e8; padding: 16px; border-radius: 6px; overflow-x: auto; }
    pre code { background: none; padding: 0; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f4f0e8; }
    blockquote { border-left: 3px solid #C48A1A; margin-left: 0; padding-left: 16px; color: #555; }
    .meta { font-size: 12px; color: #888; margin-bottom: 32px; }
    .section { margin-bottom: 32px; }
  </style>
</head>
<body>
${bodyHtml}
</body>
</html>`
}

// ─── Build PRD Markdown ──────────────────────────────────────────────────────

function buildPrdMarkdown(
  projectName: string,
  industry: string,
  prdData: PrdData,
  options: { includeToc: boolean }
): string {
  const lines: string[] = []

  lines.push(`# ${projectName}`)
  lines.push('')
  lines.push(`**Industry:** ${industry}`)
  lines.push(`**Tier:** ${prdData.tier} — ${prdData.tier_reason}`)
  if (prdData.flags.length > 0) {
    lines.push(`**Flags:** ${prdData.flags.join(', ')}`)
  }
  lines.push(`**Generated:** ${new Date().toISOString()}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  // Table of Contents
  if (options.includeToc) {
    lines.push('## Table of Contents')
    lines.push('')
    for (const section of prdData.sections) {
      if (section.content) {
        const anchor = section.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')
        lines.push(`- [${section.name}](#${anchor})`)
      }
    }
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  // Sections
  for (const section of prdData.sections) {
    if (!section.content) continue
    lines.push(`## ${section.name}`)
    lines.push('')
    lines.push(section.content)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Build SPEC.md (feature structure overview) ───────────────────────────────

interface StructurePhase {
  phase_number: number
  phase_name: string
  features: Array<{
    name: string
    description: string
    complexity?: string
    sub_features?: string[]
  }>
}

function buildSpecMarkdown(
  projectName: string,
  structureData: { phases: StructurePhase[] } | null
): string {
  const lines: string[] = []
  lines.push(`# SPEC.md — ${projectName}`)
  lines.push('')
  lines.push(`Generated by PRD Chamber`)
  lines.push(`Exported: ${new Date().toLocaleDateString('id-ID')}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  if (!structureData?.phases?.length) {
    lines.push('*No feature structure available.*')
    return lines.join('\n')
  }

  for (const phase of structureData.phases) {
    lines.push(`## Phase ${phase.phase_number}: ${phase.phase_name}`)
    lines.push('')
    for (const feature of phase.features) {
      lines.push(`### ${feature.name}`)
      if (feature.description) {
        lines.push(`_${feature.description}_`)
      }
      if (feature.sub_features?.length) {
        lines.push('')
        for (const sub of feature.sub_features) {
          lines.push(`- ${sub}`)
        }
      }
      lines.push('')
    }
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Build TASKS.md ───────────────────────────────────────────────────────────

function buildTasksMarkdown(projectName: string, tasksData: TasksData): string {
  const lines: string[] = []
  lines.push(`# TASKS.md — ${projectName}`)
  lines.push('')
  lines.push(`Generated by PRD Chamber`)
  lines.push(`Exported: ${new Date().toLocaleDateString('id-ID')}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  if (!tasksData.tasks.length) {
    lines.push('*No tasks available.*')
    return lines.join('\n')
  }

  lines.push('## Task Breakdown')
  lines.push('')

  for (const task of tasksData.tasks) {
    lines.push(`### ${task.task}`)
    lines.push('')
    lines.push(`- **Feature:** ${task.feature}`)
    lines.push(`- **Phase:** ${task.phase}`)
    lines.push(`- **Effort:** ${task.effort}`)
    lines.push(`- **Status:** ${task.is_done ? '[x] Done' : '[ ] Pending'}`)
    lines.push('')
    lines.push(task.description)
    lines.push('')
    lines.push('---')
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Build VERSIONS.json ──────────────────────────────────────────────────────

function buildVersionsJson(
  versions: Array<{ version: number; content: string; createdAt: Date | null }>
): string {
  const snapshot = versions.map(v => ({
    version: v.version,
    content: v.content,
    createdAt: v.createdAt ? new Date(v.createdAt).toISOString() : null,
  }))
  return JSON.stringify({ versions: snapshot, exportedAt: new Date().toISOString() }, null, 2)
}

// ─── Pandoc Convert ────────────────────────────────────────────────────────────

// Use absolute path — background daemon may not have /usr/bin in PATH
const PANDOC = '/usr/bin/pandoc'

async function pandocConvert(
  inputMd: string,
  toFormat: 'html' | 'pdf' | 'docx'
): Promise<{ content: Uint8Array; mimeType: string }> {
  const { exec } = await import('child_process')
  const { promisify } = await import('util')
  const execAsync = promisify(exec)

  const extMap: Record<string, string> = { html: 'html', pdf: 'pdf', docx: 'docx' }
  const mimeMap: Record<string, string> = {
    html: 'text/html; charset=utf-8',
    pdf: 'application/pdf',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  }
  const ext = extMap[toFormat]
  const ts = Date.now()
  const tmpFile = `/tmp/prd-export-${ts}.md`
  const outputFile = `/tmp/prd-export-${ts}.${ext}`

  // Write temp file
  const { writeFileSync } = await import('fs')
  writeFileSync(tmpFile, inputMd, 'utf-8')

  try {
    switch (toFormat) {
      case 'html':
        // pandoc 2.9: standalone + inline styles (no external CSS to avoid CORS)
        await execAsync(
          `"${PANDOC}" "${tmpFile}" -o "${outputFile}" --standalone --self-contained`
        )
        break
      case 'pdf':
        // Requires pdflatex installed — will error gracefully if missing
        await execAsync(
          `"${PANDOC}" "${tmpFile}" -o "${outputFile}" --pdf-engine=pdflatex`
        )
        break
      case 'docx':
        await execAsync(
          `"${PANDOC}" "${tmpFile}" -o "${outputFile}"`
        )
        break
    }

    const { readFileSync, unlinkSync } = await import('fs')
    const content = readFileSync(outputFile)
    try { unlinkSync(tmpFile) } catch {}
    try { unlinkSync(outputFile) } catch {}
    return { content: new Uint8Array(content), mimeType: mimeMap[toFormat] }
  } catch (err) {
    const { unlinkSync } = await import('fs')
    try { unlinkSync(tmpFile) } catch {}
    try { unlinkSync(outputFile) } catch {}
    throw err
  }
}

// ─── GET /api/projects/:id/export ───────────────────────────────────────────

export async function exportProject(c: Context): Promise<Response> {
  const userId = c.get('userId')
  const projectId = c.req.param('id') as string
  const format = (c.req.query('format') || 'md') as ExportFormat | 'zip'
  const includeToc = c.req.query('toc') !== 'false'
  const includeSpec = c.req.query('spec') === 'true'
  const includeTasks = c.req.query('tasks') === 'true'

  // Load project
  const [project] = await db.select().from(projects)
    .where(eq(projects.id, projectId)).limit(1)

  if (!project) return c.json({ error: 'Project not found' }, 404)
  if (project.userId !== userId) return c.json({ error: 'Forbidden' }, 403)

  // Parse prdData
  if (!project.prdData) {
    return c.json({ error: 'No PRD data found. Generate a PRD first.' }, 400)
  }

  const prdData = JSON.parse(project.prdData) as PrdData

  // Parse tasksData
  let tasksData: TasksData | null = null
  if (project.tasksData) {
    try { tasksData = JSON.parse(project.tasksData) as TasksData } catch {}
  }

  // Parse structureData
  let structureData: { phases: StructurePhase[] } | null = null
  if (project.structureData) {
    try { structureData = JSON.parse(project.structureData) as { phases: StructurePhase[] } } catch {}
  }

  // Load versions
  const versions = await db.select({
    version: projectVersions.version,
    content: projectVersions.content,
    createdAt: projectVersions.createdAt,
  })
    .from(projectVersions)
    .where(eq(projectVersions.projectId, projectId))
    .orderBy(desc(projectVersions.version))

  const projectName = project.name
  const slug = sanitizeFilename(projectName)

  // ── ZIP bundle ──────────────────────────────────────────────────────────────
  if (format === 'zip') {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const JSZip = (await import('jszip') as any).default
    const zip = new JSZip()
    const folder = zip.folder(slug)

    // Base format for main PRD (default: md)
    const prdMd = buildPrdMarkdown(projectName, project.industry, prdData, { includeToc })

    // Main PRD file
    folder?.file(`PRD-${slug}.md`, prdMd)

    // Optional SPEC.md
    if (includeSpec && structureData) {
      const specMd = buildSpecMarkdown(projectName, structureData)
      folder?.file('SPEC.md', specMd)
    }

    // Optional TASKS.md
    if (includeTasks && tasksData) {
      const tasksMd = buildTasksMarkdown(projectName, tasksData)
      folder?.file('TASKS.md', tasksMd)
    }

    // VERSIONS.json
    const versionsJson = buildVersionsJson(versions)
    folder?.file('VERSIONS.json', versionsJson)

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

    return c.body(new Uint8Array(zipBuffer), 200, {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${slug}.zip"`,
    })
  }

  // ── Single format ────────────────────────────────────────────────────────────
  const prdMd = buildPrdMarkdown(projectName, project.industry, prdData, { includeToc })
  const filename = `PRD-${slug}`

  switch (format) {
    case 'md':
      return c.body(prdMd, 200, {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}.md"`,
      })

    case 'html': {
      const htmlContent = renderMarkdownToHtml(prdMd)
      return c.body(htmlContent, 200, {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${filename}.html"`,
      })
    }

    case 'pdf':
    case 'docx': {
      try {
        const { content, mimeType } = await pandocConvert(prdMd, format)
        return new Response(content, {
          status: 200,
          headers: {
            'Content-Type': mimeType,
            'Content-Disposition': `attachment; filename="${filename}.${format}"`,
          },
        })
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err)
        // Pandoc not installed or conversion failed
        if (msg.includes('ENOENT') || msg.includes('not found') || msg.includes('spawn') || msg.includes('pandoc') || msg.includes('pdflatex')) {
          return c.json({
            error: 'Pandoc conversion failed. Check that pandoc is installed and pdflatex is available for PDF export.',
            detail: msg,
            alternative: 'Use HTML or MD format instead.',
          }, 400)
        }
        return c.json({ error: `Export failed: ${msg}` }, 500)
      }
    }

    default:
      return c.json({ error: `Unsupported format: ${format}. Use md, html, pdf, docx, or zip.` }, 400)
  }
}
