import { useState } from 'react';
import JSZip from 'jszip';
import Layout from '../components/Layout';
import { dummyPrdContent, dummyTasks, dummyVersions } from '../data/dummy';

const formats = ['MD', 'HTML', 'PDF', 'DOCX'];

// Helper: render simple markdown to plain text (for spec.md body)
function mdToText(content: string): string {
  return content
    .replace(/^#{1,3}\s+/gm, '')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/\|(.+?)\|/g, (m) => m.split('|').filter(Boolean).join(' | '))
    .replace(/---/g, '');
}

function buildSpecMd(): string {
  const sections = Object.entries(dummyPrdContent)
    .map(([key, content]) => {
      const title = key.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      return `# ${title}\n\n${content}`;
    })
    .join('\n\n---\n\n');
  return `# SPEC.md — Aplikasi POS Kopi\n\nGenerated by PRD Chamber\nExported: ${new Date().toLocaleDateString('id-ID')}\n\n---\n\n${sections}`;
}

function buildTasksMd(): string {
  const lines = ['# TASKS.md — Aplikasi POS Kopi\n', 'Generated by PRD Chamber\n\n---\n\n## Task Breakdown\n\n'];
  for (const task of dummyTasks) {
    lines.push(`### ${task.task}`);
    lines.push(`- **Feature:** ${task.feature}`);
    lines.push(`- **Phase:** ${task.phase}`);
    lines.push(`- **Effort:** ${task.effort}`);
    lines.push(`- **Status:** ${task.is_done ? '[x] Done' : '[ ] Pending'}`);
    lines.push(`- ${task.description}\n`);
  }
  return lines.join('\n');
}

export default function ExportPage() {
  const [format, setFormat] = useState('MD');
  const [includeDiagrams, setIncludeDiagrams] = useState(true);
  const [includeToc, setIncludeToc] = useState(true);
  const [includeSpec, setIncludeSpec] = useState(false);
  const [includeTasks, setIncludeTasks] = useState(false);
  const [isZipping, setIsZipping] = useState(false);

  const handleDownloadSingle = () => {
    alert(`Downloading ${format}...`);
  };

  const handleDownloadZip = async () => {
    setIsZipping(true);
    try {
      const zip = new JSZip();
      const folder = zip.folder('prd-chamber-aplikasi-pos-kopi');

      // Always include the main PRD file
      const prdContent = format === 'MD'
        ? buildSpecMd()
        : mdToText(buildSpecMd());

      const ext = format === 'MD' ? 'md' : 'txt';
      folder?.file(`PRD-Aplikasi-POS-Kopi.${ext}`, prdContent);

      // Optionally include SPEC.md
      if (includeSpec) {
        folder?.file('SPEC.md', buildSpecMd());
      }

      // Optionally include TASKS.md
      if (includeTasks) {
        folder?.file('TASKS.md', buildTasksMd());
      }

      // Include version history as JSON
      folder?.file('VERSIONS.json', JSON.stringify(dummyVersions, null, 2));

      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'prd-chamber-aplikasi-pos-kopi.zip';
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error(err);
      alert('Failed to generate ZIP.');
    } finally {
      setIsZipping(false);
    }
  };

  return (
    <Layout showBack>
      <h1 style={{ fontFamily: 'var(--font-mono)', fontSize: 18, fontWeight: 700, letterSpacing: '0.04em', textTransform: 'uppercase', color: 'var(--text-primary)', marginBottom: 16 }}>
        Export PRD
      </h1>

      <div className="term-panel" style={{ padding: '18px 22px', marginBottom: 14 }}>
        <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 12 }}>
          <span style={{ color: 'var(--accent)' }}>▸ </span>FORMAT
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          {formats.map(f => (
            <button
              key={f}
              onClick={() => setFormat(f)}
              className={format === f ? 'term-btn-accent' : 'term-btn'}
              style={{ fontSize: 10 }}
            >
              {format === f ? '[•]' : '[ ]'} {f}
            </button>
          ))}
        </div>
      </div>

      <div className="term-panel" style={{ padding: '18px 22px', marginBottom: 14 }}>
        <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 10 }}>
          <span style={{ color: 'var(--accent)' }}>▸ </span>OPTIONS
        </div>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--text-secondary)', marginBottom: 6, cursor: 'pointer' }}>
          <input type="checkbox" checked={includeDiagrams} onChange={e => setIncludeDiagrams(e.target.checked)} />
          Include Mermaid diagrams
        </label>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--text-secondary)', marginBottom: 6, cursor: 'pointer' }}>
          <input type="checkbox" checked={includeToc} onChange={e => setIncludeToc(e.target.checked)} />
          Include Table of Contents
        </label>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--text-secondary)', cursor: 'pointer' }}>
          <input type="checkbox" checked={includeSpec} onChange={e => setIncludeSpec(e.target.checked)} />
          Include SPEC.md (all sections bundled)
        </label>
        <label style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 11, color: 'var(--text-secondary)', cursor: 'pointer' }}>
          <input type="checkbox" checked={includeTasks} onChange={e => setIncludeTasks(e.target.checked)} />
          Include TASKS.md (task breakdown)
        </label>
      </div>

      <div className="term-panel" style={{ padding: '18px 22px', marginBottom: 18 }}>
        <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 10 }}>
          <span style={{ color: 'var(--accent)' }}>▸ </span>BUNDLE AS ZIP
        </div>
        <p style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 12 }}>
          Download all selected files as a single ZIP archive.
          {' '}
          <span style={{ color: 'var(--accent)' }}>
            {includeSpec && 'SPEC.md + '}
            {includeTasks && 'TASKS.md + '}
            PRD.{format === 'MD' ? 'md' : 'txt'}
            {(!includeSpec && !includeTasks) ? ' (basic)' : ''}
            {' + VERSIONS.json'}
          </span>
        </p>
        <button
          className="term-btn-accent"
          onClick={handleDownloadZip}
          disabled={isZipping}
          style={{ opacity: isZipping ? 0.6 : 1 }}
        >
          {'>'} {isZipping ? 'GENERATING...' : 'DOWNLOAD AS ZIP'}
        </button>
      </div>

      <button className="term-btn" onClick={handleDownloadSingle}>
        {'>'} DOWNLOAD {format} ONLY
      </button>
    </Layout>
  );
}
