import Layout from '../components/Layout';
import MarkdownViewer from '../components/MarkdownViewer';
import { dummyPrdContent } from '../data/dummy';

const sectionMeta: Record<string, { label: string }> = {
  'executive-summary':         { label: 'Executive Summary' },
  'problem-statement':         { label: 'Problem Statement' },
  'core-features':             { label: 'Core Features' },
  'user-flow':                 { label: 'User Flow / Journey' },
  'functional-requirements':   { label: 'Functional Requirements' },
  'architecture':              { label: 'System Architecture' },
  'database-schema':           { label: 'Database Schema' },
};

function Section({ id }: { id: string }) {
  const meta = sectionMeta[id] ?? { label: id.replace(/-/g, ' ') };

  return (
    <section
      key={id}
      style={{ marginBottom: 36, scrollMarginTop: 80 }}
    >
      {/* Section label */}
      <div style={{
        fontSize: 10,
        fontFamily: 'var(--font-mono)',
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: 'var(--text-muted)',
        marginBottom: 14,
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        paddingBottom: 8,
        borderBottom: '1px solid var(--border)',
      }}>
        <span style={{ color: 'var(--accent)' }}>▸</span>
        {meta.label}
      </div>

      {/* Content */}
      <MarkdownViewer content={dummyPrdContent[id]} />
    </section>
  );
}

export default function SharePage() {
  const sectionIds = Object.keys(dummyPrdContent);

  return (
    <Layout showBack showStepper={false}>
      {/* Status bar */}
      <div className="status-bar" style={{ marginBottom: 20 }}>
        <span>SHARED DOCUMENT — READ ONLY</span>
        <span style={{ color: 'var(--text-muted)' }}>TOKEN: xyz-abc-123</span>
      </div>

      {/* Document header */}
      <div style={{ marginBottom: 28 }}>
        <h1 style={{
          fontFamily: 'var(--font-mono)',
          fontSize: 18,
          fontWeight: 700,
          color: 'var(--accent)',
          marginBottom: 4,
        }}>
          Aplikasi POS Kopi
        </h1>
        <p style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 0 }}>
          Product Requirements Document — Generated by PRD Chamber
        </p>
      </div>

      {/* Sections */}
      <div className="term-panel" style={{ padding: '28px 32px' }}>
        {sectionIds.map(id => (
          <Section id={id} key={id} />
        ))}
      </div>

      {/* Footer */}
      <div style={{
        marginTop: 16,
        padding: '12px 0',
        borderTop: '1px solid var(--border)',
        fontSize: 10,
        color: 'var(--text-muted)',
        textAlign: 'center',
        fontFamily: 'var(--font-mono)',
      }}>
        SHARED VIA PRD CHAMBER — READ ONLY DOCUMENT
      </div>
    </Layout>
  );
}
