#!/bin/bash
# chronicle-trigger.sh — Trigger chronicle from git hooks
# Usage: bash chronicle-trigger.sh --trigger=commit --project=prd-chamber ...

set -e

TRIGGER=""
PROJECT=""
COMMIT_HASH=""
COMMIT_MSG=""
MILESTONE_TYPE=""
BRANCH=""
PUSHED_COMMITS=""
PUSH_TYPE=""

# Parse arguments (handle both --key=value and --key value)
while [[ $# -gt 0 ]]; do
    ARG="$1"
    
    # Handle --key=value format
    if [[ "$ARG" == --*=* ]]; then
        KEY="${ARG#--}"
        KEY="${KEY%%=*}"
        VALUE="${ARG#--*=}"
    else
        KEY="${ARG#--}"
        VALUE="$2"
        if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
            shift
        fi
    fi
    
    case "$KEY" in
        trigger) TRIGGER="$VALUE" ;;
        project) PROJECT="$VALUE" ;;
        commit) COMMIT_HASH="$VALUE" ;;
        message) COMMIT_MSG="$VALUE" ;;
        milestone) MILESTONE_TYPE="$VALUE" ;;
        branch) BRANCH="$VALUE" ;;
        commits) PUSHED_COMMITS="$VALUE" ;;
        type) PUSH_TYPE="$VALUE" ;;
    esac
    
    shift
done

# Get vault path
VAULT_BASE="$HOME/zermes-vault"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

# Create chronicle entry based on trigger
chronicle_file="$VAULT_BASE/60-logs/chronicle/$(date '+%Y-%m-%d')-$PROJECT-chronicle.md"

# Ensure chronicle file exists
if [ ! -f "$chronicle_file" ]; then
    cat > "$chronicle_file" << EOF
# $PROJECT Chronicle — $(date '+%Y-%m-%d')

> Auto-generated by Chronicle Trigger
> Triggers: git commits, pushes

---
EOF
fi

case "$TRIGGER" in
    commit)
        # Build entry
        ENTRY="
## $TIMESTAMP — GIT COMMIT
**Project:** $PROJECT
**Commit:** \`$COMMIT_HASH\`
**Message:** $COMMIT_MSG
**Files:** Auto-detected

**Status:** ✅ COMMITTED
"

        # Add milestone info if detected
        if [ -n "$MILESTONE_TYPE" ]; then
            ENTRY="$ENTRY
**Milestone:** $MILESTONE_TYPE
"
        fi

        # Append to chronicle
        echo "$ENTRY" >> "$chronicle_file"
        echo "✓ Chronicle entry added for commit $COMMIT_HASH"
        ;;
    
    push)
        ENTRY="
## $TIMESTAMP — GIT PUSH
**Project:** $PROJECT
**Branch:** $BRANCH
**Commits:** $PUSHED_COMMITS
**Type:** $PUSH_TYPE

**Status:** ✅ PUSHED
"

        echo "$ENTRY" >> "$chronicle_file"
        echo "✓ Chronicle entry added for push to $BRANCH"
        ;;
    
    *)
        echo "Unknown trigger: $TRIGGER"
        exit 1
        ;;
esac

# Git sync vault
cd "$VAULT_BASE" 2>/dev/null || exit 0
git add -A 2>/dev/null
git commit -m "chore: chronicle update from $TRIGGER" 2>/dev/null || true
git push 2>/dev/null || true

echo "✓ Vault synced"
